name: prescribo
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=2.18.0-151.0.dev <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  pin_code_fields: ^8.0.1
  intl: ^0.18.0
  google_fonts: ^6.1.0
  rive: ^0.12.4
  flutter_barcode_scanner: ^2.0.0
  image_picker: ^1.0.7
  pdf: 3.10.7
  lottie: ^1.4.3
  smooth_page_indicator: ^1.1.0
  camera: ^0.10.5+9
  firebase_core: ^2.25.4
  cloud_firestore: ^4.3.2
  firebase_storage: ^11.0.11
  file_picker: ^5.2.5
  easy_pdf_viewer: ^1.0.6
  firebase_auth: ^4.17.4
  carousel_slider: ^4.2.1
  flutter_native_splash: ^2.3.10
  get: ^4.6.6
  get_storage: ^2.1.1
  iconsax: ^0.0.8
  url_launcher: ^6.1.12
  http: ^1.1.0
  logger: ^2.0.1

  
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/animation/onloading_1.json
    - assets/animation/onloading_2.json
    - assets/animation/onloading_3.json
    - assets/fonts/
    - assets/new_assets/logos/
    - assets/new_assets/icons/
    - assets/new_assets/images/
    - assets/new_assets/fonts/
    - assets/new_assets/images/on_boarding_images/sammy-line-delivery.gif
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/InterBold.ttf
          weight: 700
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/fonts/PlusJakartaSansMedium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSansSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSansBold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSansRomanBold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSansRomanLight.ttf
          weight: 300
